// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimplifiedCollageSystem.DomainModels;

namespace SimplifiedCollageSystem.DomainModels.Migrations
{
    [DbContext(typeof(CollageDBContext))]
    [Migration("20201118180318_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimplifiedCollageSystem.DomainModels.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FullName");

                    b.Property<string>("MobilePhone");

                    b.HasKey("StudentNumber");

                    b.ToTable("Students");

                    b.HasData(
                        new { StudentNumber = 1, EmailAddress = "dushko.videski@gmail.com", FullName = "Dushko Videski", MobilePhone = "+38971252980" }
                    );
                });

            modelBuilder.Entity("SimplifiedCollageSystem.DomainModels.Subject", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Credits");

                    b.Property<int>("Semestar");

                    b.Property<int>("StudentId");

                    b.HasKey("Name");

                    b.HasIndex("StudentId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new { Name = "Math", Credits = 170, Semestar = 1, StudentId = 1 },
                        new { Name = "History", Credits = 200, Semestar = 2, StudentId = 1 }
                    );
                });

            modelBuilder.Entity("SimplifiedCollageSystem.DomainModels.Subject", b =>
                {
                    b.HasOne("SimplifiedCollageSystem.DomainModels.Student", "Student")
                        .WithMany("Subjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
